FROM node:18

WORKDIR /usr/src/app

# Install dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn

ENV PATH=/usr/local/myapp/node_modules/.bin:$PATH

# Copy source
COPY . .

CMD ["yarn", "start:dev"]